package pl.pawlo.teacherapp.domain;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum SchoolClass {
    CLASS_1_PODSTAWOWKA("1 PODSTAWOWKA"),
    CLASS_2_PODSTAWOWKA("2 PODSTAWOWKA"),
    CLASS_3_PODSTAWOWKA("3 PODSTAWOWKA"),
    CLASS_4_PODSTAWOWKA("4 PODSTAWOWKA"),
    CLASS_5_PODSTAWOWKA("5 PODSTAWOWKA"),
    CLASS_6_PODSTAWOWKA("6 PODSTAWOWKA"),
    CLASS_7_PODSTAWOWKA("7 PODSTAWOWKA"),
    CLASS_8_PODSTAWOWKA("8 PODSTAWOWKA"),
    CLASS_1_LICEUM("1 LICEUM"),
    CLASS_2_LICEUM("2 LICEUM"),
    CLASS_3_LICEUM("3 LICEUM"),
    CLASS_1_TECHNIKUM("1 TECHNIKUM"),
    CLASS_2_TECHNIKUM("2 TECHNIKUM"),
    CLASS_3_TECHNIKUM("3 TECHNIKUM"),
    CLASS_4_TECHNIKUM("4 TECHNIKUM"),
    CLASS_MATURALNA("KLASA MATURALNA");

    private final String label;



}
